### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by amyspark-ng** [Nighmared/RAD#1]
I get this error and i don't really know why, in links i have the ruins of the empire part one
![image](https://user-images.githubusercontent.com/92493175/233895582-ab22de37-c8c0-48e6-ac6a-7b10bfbb7b2c.png)

**Comment by Nighmared** [comment]
Hi! Sorry for the wait, I'm on holidays and didn't see your issue until now, I will try to reproduce and fix this within the next two days :)

Thanks for reporting the issue!

**Comment by amyspark-ng** [comment]
It's okay no worries :D

**Comment by Nighmared** [comment]
@amyspark-ng 
Okay with the latest release (v1.22) or just the latest push to the repo it should work again, sorry for the long wait [it was obviously not within the next two days....... ] - the website layout changed so the script couldn't find the images anymore...
