### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sd704** [Nighmared/RAD#2]
![Screenshot (276)](https://github.com/Nighmared/RAD/assets/51424617/ac6e91b1-5604-46b1-aad0-f2c6227cf0b0)
I am getting this error while trying to download 
Batman by Jeph Loeb & Tim Sale Omnibus TPB (Part 01) ; https://readallcomics.com/batman-by-jeph-loeb-tim-sale-omnibus-tpb-part-01/
Found out this error only happens with certain comics only

**Comment by deepdivered** [comment]
This happened on ever comic I tried today.

Krampus 2 ; https://readallcomics.com/krampus-002-2014/
Krampus 3 ; https://readallcomics.com/krampus-003-2014/
Krampus 4 ; https://readallcomics.com/krampus-004-2014/
Krampus 5 ; https://readallcomics.com/krampus-005-2014/
Evil Dead 2 Revenge Of Krampus 1 ; https://readallcomics.com/evil-dead-2-revenge-of-krampus-001-2016/
Evil Dead 2 Revenge Of Krampus 2 ; https://readallcomics.com/evil-dead-2-revenge-of-krampus-002-2016/

**Comment by deepdivered** [comment]
`Found 1 Entries
Krampus 5                                Downloading  [     Krampus 5                                Downloading  [     Krampus 5                                Downloading  [     Krampus 5                                Downloading  [|    Krampus 5                                Downloading  [|    Krampus 5                                Downloading  [||   Krampus 5                                Downloading  [||   Krampus 5                                Downloading  [||   Krampus 5                                Downloading  [|||  Krampus 5                                Downloading  [|||  Krampus 5                                Downloading  [|||| Krampus 5                                Downloading  [|||| Krampus 5                                Downloading  [|||| Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Krampus 5                                Downloading  [|||||Traceback (most recent call last):           ]
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 240, in <module>
  File "<string>", line 57, in main
  File "<string>", line 164, in handle_entry
IndexError: list index out of range

[Program finished]`

**Comment by Nighmared** [comment]
I'm sorry, I completely forgot about this project event existing. Even worse the issue was seemingly very minor.

should be fixed on main as soon as the pr is merged, I hope it works for both of you and thanks for your patience :)
